# Generated by Django 3.0.8 on 2020-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmanager', '0002_auto_20200729_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate_per_hour',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
