# Generated by Django 3.0.8 on 2020-08-22 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginmanager', '0004_auto_20200808_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, help_text='Email', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='first name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='last name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate_per_hour',
            field=models.FloatField(blank=True, help_text='Rate Per Hour', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
