# Generated by Django 3.0.8 on 2020-08-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginmanager', '0005_auto_20200822_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
