# Generated by Django 3.0.8 on 2020-08-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginmanager', '0006_auto_20200822_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
    ]
