# Generated by Django 3.0.8 on 2020-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
