# Generated by Django 3.0.8 on 2020-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='acknowledge',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
