# Generated by Django 3.0.8 on 2020-08-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_acknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=600, verbose_name='message'),
        ),
    ]
