# Generated by Django 3.0.8 on 2020-08-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20200822_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='acknowledge',
            field=models.CharField(blank=True, help_text='Acknowledge', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date Created', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(help_text='message', max_length=600),
        ),
    ]
