# Generated by Django 3.0.8 on 2020-07-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(max_length=100)),
                ('checkin_message', models.CharField(blank=True, max_length=500, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('checkout_message', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
