# Generated by Django 3.0.8 on 2020-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_auto_20200806_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
