# Generated by Django 3.0.8 on 2020-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0003_auto_20200808_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='checkin_time',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
