# Generated by Django 3.0.8 on 2020-08-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0006_auto_20200808_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='checkout_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
