# Generated by Django 3.0.8 on 2020-08-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0007_auto_20200808_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', models.TimeField()),
            ],
        ),
    ]
