# Generated by Django 3.0.8 on 2020-08-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0008_breaktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='checkin_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
