# Generated by Django 3.0.8 on 2020-08-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0009_auto_20200808_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'verbose_name': 'Daily Log', 'verbose_name_plural': 'Daily Logs'},
        ),
    ]
