# Generated by Django 3.0.8 on 2020-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
