# Generated by Django 3.0.3 on 2022-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desctiption', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('premium', models.BooleanField(default=True)),
            ],
        ),
    ]
